# Generated by Django 6.0.7 on 2026-08-03 09:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسم الوظيفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صالحًا.', regex='^[0-9+\\-\\s()]{7,30}$')], verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('qualification', models.CharField(choices=[('SECONDARY', 'ثانوي'), ('DIPLOMA', 'دبلوم'), ('BACHELOR', 'بكالوريوس'), ('MASTER', 'ماجستير'), ('PHD', 'دكتوراة'), ('OTHER', 'أخرى')], max_length=20, verbose_name='المؤهل')),
                ('experience', models.TextField(verbose_name='الخبرات')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='السيرة الذاتية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'متقدم',
                'verbose_name_plural': 'متقدمون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='app_applica_full_na_707465_idx'), models.Index(fields=['phone'], name='app_applica_phone_27ddf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الشركة')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صالحًا.', regex='^[0-9+\\-\\s()]{7,30}$')], verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='app_company_name_4b92e5_idx'), models.Index(fields=['phone'], name='app_company_phone_169ca7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyJobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('required_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد المطلوبين')),
                ('fee_per_employee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الرسوم لكل موظف')),
                ('currency', models.CharField(choices=[('YER', 'ريال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], default='YER', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], db_index=True, default='OPEN', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requests', to='app.company', verbose_name='الشركة')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_requests', to='app.job', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'طلب شركة',
                'verbose_name_plural': 'طلبات الشركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم التصنيف')),
                ('type', models.CharField(choices=[('RECEIPT', 'سند قبض'), ('PAYMENT', 'سند صرف')], db_index=True, max_length=10, verbose_name='نوع السند')),
            ],
            options={
                'verbose_name': 'تصنيف سند',
                'verbose_name_plural': 'تصنيفات السندات',
                'ordering': ['type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='unique_voucher_category_name_type')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('voucher_number', models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=30, null=True, unique=True, verbose_name='رقم السند')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة وقت إنشاء السند')),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم هاتف الشركة وقت إنشاء السند')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد الشركة وقت إنشاء السند')),
                ('type', models.CharField(choices=[('RECEIPT', 'سند قبض'), ('PAYMENT', 'سند صرف')], db_index=True, max_length=10, verbose_name='نوع السند')),
                ('currency', models.CharField(choices=[('YER', 'ريال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي')], default='YER', max_length=3, verbose_name='العملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('voucher_date', models.DateField(db_index=True, verbose_name='تاريخ السند')),
                ('description', models.TextField(verbose_name='البيان')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='app.company', verbose_name='الشركة')),
                ('job_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='app.companyjobrequest', verbose_name='طلب الشركة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='app.vouchercategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'سندات',
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('NEW', 'جديد'), ('UNDER_REVIEW', 'قيد المراجعة'), ('WAITING', 'قائمة انتظار'), ('WITHDRAWN', 'انسحب'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('HIRED', 'تم التوظيف')], db_index=True, default='NEW', max_length=20, verbose_name='الحالة')),
                ('fee_per_employee_snapshot', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='رسوم الموظف وقت القبول')),
                ('employment_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ التوظيف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app.applicant', verbose_name='المتقدم')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app.companyjobrequest', verbose_name='طلب الشركة')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='app_applica_status_f75961_idx'), models.Index(fields=['job_request', 'applicant'], name='app_applica_job_req_5e8b03_idx')],
                'constraints': [models.UniqueConstraint(fields=('job_request', 'applicant'), name='unique_applicant_per_job_request')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('follow_up_date', models.DateField(db_index=True, verbose_name='تاريخ المتابعة')),
                ('note', models.TextField(verbose_name='الملاحظة')),
                ('status', models.CharField(choices=[('PENDING', 'معلقة'), ('COMPLETED', 'مكتملة')], db_index=True, default='PENDING', max_length=20, verbose_name='الحالة')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='app.applicant', verbose_name='المتقدم')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='app.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['-follow_up_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='app_followu_status_4b60d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='companyjobrequest',
            index=models.Index(fields=['status'], name='app_company_status_6fc04c_idx'),
        ),
        migrations.AddIndex(
            model_name='companyjobrequest',
            index=models.Index(fields=['company', 'job'], name='app_company_company_f7bc72_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_date'], name='app_voucher_voucher_b69a90_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_date'], name='app_voucher_company_06270b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['job_request', 'voucher_date'], name='app_voucher_job_req_56ea8f_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['type', 'voucher_date'], name='app_voucher_type_b5dc36_idx'),
        ),
    ]
