# Generated by Django 6.0.7 on 2026-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الشركة وقت إنشاء السند'),
        ),
    ]
